import { execFile } from "node:child_process";
import type { FixVerification } from "./fix-gen.ts";

function exec(cmd: string, args: string[]): Promise<string> {
  return new Promise((resolve, reject) => {
    execFile(cmd, args, { timeout: 30_000 }, (error, stdout, stderr) => {
      if (error) {
        reject(new Error(`${cmd} ${args.join(" ")} failed: ${(stderr ?? "").trim() || error.message}`));
        return;
      }
      resolve((stdout ?? "").trim());
    });
  });
}

async function checkGhInstalled(): Promise<void> {
  try {
    await exec("gh", ["--version"]);
  } catch {
    throw new Error("GitHub CLI (gh) is required for --pr. Install it: https://cli.github.com");
  }
}

function getCurrentBranch(): Promise<string> {
  return exec("git", ["rev-parse", "--abbrev-ref", "HEAD"]);
}

function sanitizeForMarkdown(text: string): string {
  return text.replace(/[`$\\]/g, "\\$&");
}

export async function createFixPr(
  fixes: FixVerification[]
): Promise<string> {
  const verified = fixes.filter((f) => f.status === "verified");
  if (verified.length === 0) {
    throw new Error("No verified fixes to commit.");
  }

  await checkGhInstalled();

  const baseBranch = await getCurrentBranch();
  if (baseBranch === "HEAD") {
    throw new Error("Cannot create PR from detached HEAD. Check out a branch first.");
  }

  const timestamp = Date.now();
  const fixBranch = `brunt/fix-${timestamp}`;

  await exec("git", ["checkout", "-b", fixBranch]);

  try {
    const files = [...new Set(verified.map((f) => f.filePath))];
    await exec("git", ["add", ...files]);

    const fixSummary = verified
      .map((f) => `- ${f.finding.severity.toUpperCase()} ${f.finding.file}:${f.finding.line}: ${sanitizeForMarkdown(f.finding.title)}`)
      .join("\n");

    const message = `fix: auto-fix ${verified.length} issue${verified.length === 1 ? "" : "s"} found by brunt

${fixSummary}

Fixes verified against generated proof tests.`;

    await exec("git", ["commit", "-m", message]);
    await exec("git", ["push", "-u", "origin", fixBranch]);

    const body = `## Brunt Auto-Fix

${verified.length} issue${verified.length === 1 ? "" : "s"} found and fixed automatically.

### Fixes

${verified.map((f) => `- **${f.finding.severity.toUpperCase()}** \`${sanitizeForMarkdown(f.finding.file)}:${f.finding.line}\`: ${sanitizeForMarkdown(f.finding.title)} (verified in ${f.attempts} attempt${f.attempts === 1 ? "" : "s"})`).join("\n")}

### Verification

All fixes were verified by running generated proof tests. Each test was designed to fail against the buggy code and pass after the fix.

---
Generated by [brunt](https://github.com/anfocic/brunt)`;

    const prUrl = await exec("gh", [
      "pr", "create",
      "--base", baseBranch,
      "--head", fixBranch,
      "--title", `fix: brunt auto-fix ${verified.length} issue${verified.length === 1 ? "" : "s"}`,
      "--body", body,
    ]);

    await exec("git", ["checkout", baseBranch]);

    return prUrl;
  } catch (err) {
    await exec("git", ["checkout", baseBranch]).catch(() => {});
    throw err;
  }
}
